image: ubuntu

branches:
    only:
      - master

install:
    - cd /home/appveyor/projects
    - git clone https://github.com/ampl/gsl
    - bash regionsmt/.install/gsl.sh
    - cd regionsmt

build_script:
    - make

test_script:
    - ./RegionsMT-Release -T
    - ./RegionsMT-Debug -T

after_test:
    - make clean


