os: linux
dist: xenial
language: c

before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get install make

compiler: gcc
#  - clang
#  - gcc

#os:
#  - linux
#  - osx

install:
  - cd ..
  - makedir gsl
  - cd gsl

script: make # ./configure && make && make test
