os: linux
dist: trusty
sudo: required
language: c

before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get install make
  - make -v


compiler: gcc
#  - clang
#  - gcc

#os:
#  - linux
#  - osx

install:

script: make # ./configure && make && make test
